#
###################################
# Site wide configuration
####################################
#
title:       "Leonids Jekyll theme"
description: "Clean Jekyll blog theme called Leonids."
url:         # the base hostname & protocol for your site
url: "http://hurlatunde.github.io" # the base hostname & protocol for your site
twitter_username: hurlatunde
github_username:  hurlatunde

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
paginate_path: "/articles/page:num/"
paginate: 10

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

# Site Owner configuration
owner:
  username: Hurlatunde
  name: Hurlatunde
  avatar: https://z-1-scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/13612349_10205524814554405_7966782029174826798_n.jpg?oh=ccadbbd56049737eb7f3e887f1eb5235&oe=58280D54
  job: "Backend-End Developer"
  bio: "Write about yourself"
  email: hurlatunde@gmail.com
  disqus-shortname: hurlatundegithubio
  facebook: https://www.facebook.com/Olatunde.owokoniran
  google:
    plus:
    analytics: UA-81222589-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hurlatunde
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: hurlatunde
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

# Gems
gems: [jekyll-paginate]